/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Wed Feb 25 27:06:29 BRT 2025
* 
* Call the script: _dummy = this execvm "BackpackCrate.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

  _this addBackpackCargoGlobal ["B_FieldPack_blk",2];
  _this addBackpackCargoGlobal ["B_Carryall_khk",2];
  _this addBackpackCargoGlobal ["B_Carryall_mcamo",2];
  _this addBackpackCargoGlobal ["B_Carryall_oli",2];
  _this addBackpackCargoGlobal ["B_Carryall_ocamo",2];
  _this addItemCargoGlobal ["V_Chestrig_oli",3];
  _this addItemCargoGlobal ["V_Chestrig_khk",3];
  
  _this additemcargoGlobal ["H_Booniehat_tan",5];
  _this additemcargoGlobal ["G_Lady_Mirror",5];
  _this additemcargoGlobal ["H_Watchcap_sgg",5];
  _this additemcargoGlobal ["H_Bandanna_sand",5];
  _this additemcargoGlobal ["H_Bandanna_surfer_grn",5];
  _this additemcargoGlobal ["H_HelmetSpecO_blk",5];
  _this additemcargoGlobal ["G_Bandanna_oli",5];
  _this additemcargoGlobal ["G_Lady_Red",5];
  _this additemcargoGlobal ["H_Watchcap_camo",5];
  _this additemcargoGlobal ["G_Spectacles_Tinted",5];
  _this additemcargoGlobal ["H_Bandanna_cbr",5];
  _this additemcargoGlobal ["H_Beret_blk",5];
  _this additemcargoGlobal ["H_Beret_02",5];
  _this additemcargoGlobal ["H_Booniehat_grn",5];
  _this additemcargoGlobal ["H_HelmetCrew_I",5];
  _this additemcargoGlobal ["H_HelmetCrew_B",5];
  _this additemcargoGlobal ["H_HelmetB",5];
  _this additemcargoGlobal ["G_Balaclava_blk",5];
  _this additemcargoGlobal ["H_BandMask_reaper",5];
  _this additemcargoGlobal ["H_Cap_red",5];
  _this additemcargoGlobal ["H_HelmetCrew_O",5];
  _this additemcargoGlobal ["H_HelmetB_snakeskin",5];
  _this additemcargoGlobal ["H_HelmetO_oucamo",5];
  _this additemcargoGlobal ["H_HelmetB_plain_blk",5];
  _this additemcargoGlobal ["H_HelmetB_light_grass",5];
  _this additemcargoGlobal ["H_Cap_blk_ION",5];
  _this additemcargoGlobal ["G_Sport_Blackyellow",5];
  _this additemcargoGlobal ["H_HelmetB_grass",5];
  _this additemcargoGlobal ["G_Bandanna_tan",5];
  _this additemcargoGlobal ["G_Balaclava_lowprofile",5];
  _this additemcargoGlobal ["H_Beret_Colonel",5];
  _this additemcargoGlobal ["H_Watchcap_blk",5];
  _this additemcargoGlobal ["H_Beret_blk_POLICE",5];
  _this additemcargoGlobal ["H_Bandanna_sgg",5];
  _this additemcargoGlobal ["G_Shades_Blue",5];
  _this additemcargoGlobal ["G_Bandanna_shades",5];
  _this additemcargoGlobal ["H_TurbanO_blk",5];
  _this additemcargoGlobal ["G_Aviator",5];
  _this additemcargoGlobal ["G_Tactical_Clear",5];
  _this additemcargoGlobal ["G_Squares_Tinted",5];
  _this additemcargoGlobal ["H_HelmetB_sand",5];
  _this additemcargoGlobal ["H_Booniehat_dgtl",5];
  _this additemcargoGlobal ["H_HelmetB_paint",5];
  _this additemcargoGlobal ["H_Cap_blk",5];
  _this additemcargoGlobal ["H_HelmetB_light_desert",5];
  _this additemcargoGlobal ["H_Beret_grn_SF",5];
  _this additemcargoGlobal ["H_Bandanna_camo",5];
};
